### ISSUE TITLE
1.0.0 픽스

### ISSUE THREAD

**Issue by lee-ji-hoon** [boostcampwm-2022/android04-BEEP#190]

**Comment by lee-ji-hoon** [comment]
naverMap 로직 변경 필요

- 브랜드나 기프티콘 변경시 마커도 같이 변경해줘야 함

**Comment by yangsooplus** [comment]
사용완료 기프티콘 미구현
- 메뉴 자체를 임시로 숨김

**Comment by lee-ji-hoon** [comment]
상세화면
- 데이터 수정할 때 유저가 브랜드명을 아예 지우고서 저장을 누르면 막기

**Comment by lee-ji-hoon** [comment]
홈에서 더보기로 갈때 바텀 네비게이션 작동안함

**Comment by lee-ji-hoon** [comment]
D-day 문제 있던거 해결

**Comment by lee-ji-hoon** [comment]
Map에서 쿠폰 사용하고 돌아왔을때 존재하지 않는 브랜드들은 없애줘야 함

**Comment by lee-ji-hoon** [comment]
만료 칩 색상 바꿔주기

**Comment by lee-ji-hoon** [comment]
디테일 페이지에서 수정 버튼 누르고서 EditText 어떻게 강조할지 + 다 지우고 나서 입력이 너무어렵다.

**Comment by lee-ji-hoon** [comment]
위젯이 짤리는 문제
